package view;

import model.ClienteWrite;
import control.Cliente;
import tablemodel.ClienteTM;
import java.awt.Color;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import dao.ClienteDAO;
import dao.Conexao;
import java.sql.Connection;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author aluno
 */
public final class ClienteView extends javax.swing.JFrame {
    //iniciando variáveis globais
            //Gerador chama a class tabela e dá um nome
                public static ClienteTM Modelo;
            //..........................................

            //index é responsável por coletar o indice da tabela
                public static int index;
                
            //..................................................

            //modoDep é uma variável que coleta Strings para ativar e desativar botões com um switch case
                String modoDep;
            //....................................................
                Connection con;
                 
            //BackGround pega o backGround da tabela 
                Color BackGround = Color.CYAN;
            //.......................................
    //...................................
    /**
     * Creates new form InterfaceGra
     */
    public ClienteView() {
            
           
            initComponents();
        
        //RelativeNull é para a tela ficar centralizada
            setLocationRelativeTo(null);
        //.............................................
        
        //Modo "Excluir" desativa a maioria dos botões
            modoDep = "Excluir";
        //..........................................
        
        //Chama a função do modoDep
            ManipulaInterfaceDep();
        //.........................
        
            LoadTable();
    }
   
    public void LoadTable(){
        //Modelo recebe a criação de tabelas
            Modelo = new ClienteTM(ClienteDAO.cliente());
        //..................................
        
        //Seta o conteúdo de modelo na tabela local
            jTabela.setModel(Modelo);
        //.........................................
        
        //Define as larguras de cada posição
        jTabela.getColumnModel().getColumn(0).setPreferredWidth(140);
        jTabela.getColumnModel().getColumn(1).setPreferredWidth(120);
        jTabela.getColumnModel().getColumn(2).setPreferredWidth(120);
        jTabela.getColumnModel().getColumn(3).setPreferredWidth(50);
        jTabela.getColumnModel().getColumn(4).setPreferredWidth(130);
        jTabela.getColumnModel().getColumn(5).setPreferredWidth(100);
        jTabela.getColumnModel().getColumn(6).setPreferredWidth(130);
        jTabela.getColumnModel().getColumn(7).setPreferredWidth(170);
        jTabela.getColumnModel().getColumn(8).setPreferredWidth(100);
        jTabela.getColumnModel().getColumn(9).setPreferredWidth(100);
        jTabela.getColumnModel().getColumn(10).setPreferredWidth(100);
        jTabela.getColumnModel().getColumn(11).setPreferredWidth(50);
        jTabela.getColumnModel().getColumn(12).setPreferredWidth(100);
        //..................................
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupo_sexo = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jNome = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jbCadastrar = new javax.swing.JButton();
        jIdade = new javax.swing.JTextField();
        jCidade = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jrMasculino = new javax.swing.JRadioButton();
        jrFeminino = new javax.swing.JRadioButton();
        jbLimpar = new javax.swing.JButton();
        jCpf = new javax.swing.JFormattedTextField();
        jFone = new javax.swing.JFormattedTextField();
        jCelular = new javax.swing.JFormattedTextField();
        jLabel7 = new javax.swing.JLabel();
        jEmail = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jCep = new javax.swing.JFormattedTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTabela = new javax.swing.JTable();
        jBairro = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jNumero = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jEstado = new javax.swing.JTextField();
        jbNovo = new javax.swing.JButton();
        jSalvar = new javax.swing.JButton();
        jExcluir = new javax.swing.JButton();
        jCLinha = new javax.swing.JButton();
        jEdit = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jRua = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de clientes");
        setBackground(new java.awt.Color(208, 230, 227));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jNome.setToolTipText("");
        jNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNomeActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(0, 204, 255));
        jLabel1.setFont(new java.awt.Font("Quartz", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(73, 188, 227));
        jLabel1.setText("Cadastro de clientes");

        jbCadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/group.png"))); // NOI18N
        jbCadastrar.setText("Cadastrar");
        jbCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCadastrarActionPerformed(evt);
            }
        });

        jIdade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jIdadeActionPerformed(evt);
            }
        });

        jCidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCidadeActionPerformed(evt);
            }
        });

        jLabel2.setText("NOME");
        jLabel2.setToolTipText("");

        jLabel3.setText("CPF");

        jLabel4.setText("CIDADE");

        jLabel5.setText("FIXO");

        jLabel6.setText("IDADE");

        grupo_sexo.add(jrMasculino);
        jrMasculino.setText("Masculino");

        grupo_sexo.add(jrFeminino);
        jrFeminino.setText("Feminino");

        jbLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/trash.png"))); // NOI18N
        jbLimpar.setText("Limpar campos");
        jbLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLimparActionPerformed(evt);
            }
        });

        try {
            jCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jCpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCpfActionPerformed(evt);
            }
        });

        try {
            jFone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFoneActionPerformed(evt);
            }
        });

        try {
            jCelular.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) 9####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jCelular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCelularActionPerformed(evt);
            }
        });

        jLabel7.setText("CELULAR");

        jLabel8.setText("CEP");

        jLabel9.setText("E-MAIL");

        try {
            jCep.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jCep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCepActionPerformed(evt);
            }
        });

        jTabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NOME", "CPF", "FONE", "CIDADE", "E-MAIL", "CELULAR", "IDADE", "BAIRRO", "ESTADO", "NUMERO", "SEXO", "CEP"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTabela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabelaMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jTabelaMouseReleased(evt);
            }
        });
        jTabela.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTabelaKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTabelaKeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(jTabela);
        if (jTabela.getColumnModel().getColumnCount() > 0) {
            jTabela.getColumnModel().getColumn(1).setPreferredWidth(20);
            jTabela.getColumnModel().getColumn(2).setPreferredWidth(20);
            jTabela.getColumnModel().getColumn(5).setPreferredWidth(30);
            jTabela.getColumnModel().getColumn(6).setPreferredWidth(1);
            jTabela.getColumnModel().getColumn(8).setPreferredWidth(3);
            jTabela.getColumnModel().getColumn(9).setPreferredWidth(1);
            jTabela.getColumnModel().getColumn(10).setPreferredWidth(4);
            jTabela.getColumnModel().getColumn(11).setPreferredWidth(1);
        }

        jBairro.setToolTipText("");

        jLabel10.setText("BAIRRO");
        jLabel10.setToolTipText("");

        jNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNumeroActionPerformed(evt);
            }
        });

        jLabel11.setText("NÚMERO");

        jLabel12.setText("ESTADO");

        jbNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/document-add.png"))); // NOI18N
        jbNovo.setText("Novo");
        jbNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNovoActionPerformed(evt);
            }
        });

        jSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/input-checked-outline.png"))); // NOI18N
        jSalvar.setText("Salvar alterações");
        jSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSalvarActionPerformed(evt);
            }
        });

        jExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/th-list-outline.png"))); // NOI18N
        jExcluir.setText("Limpar tabela");
        jExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jExcluirActionPerformed(evt);
            }
        });

        jCLinha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/user-delete-outline.png"))); // NOI18N
        jCLinha.setText("Limpar linha");
        jCLinha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCLinhaActionPerformed(evt);
            }
        });

        jEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/business-card.png"))); // NOI18N
        jEdit.setText("Editar");
        jEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEditActionPerformed(evt);
            }
        });

        jLabel13.setText("Rua");

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cliente.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jbNovo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbCadastrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jIdade, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jFone, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jEmail, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCpf, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jNome, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jNumero))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(379, 379, 379)
                                        .addComponent(jLabel14)
                                        .addGap(67, 67, 67))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(46, 46, 46)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(12, 12, 12)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jEstado)
                                                    .addComponent(jBairro, javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jCep, javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jCelular, javax.swing.GroupLayout.Alignment.TRAILING)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(12, 12, 12)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jRua)
                                                    .addComponent(jCidade))))
                                        .addGap(63, 63, 63)
                                        .addComponent(jrMasculino, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(61, 61, 61)
                                        .addComponent(jrFeminino, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(10, 10, 10))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jbLimpar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jExcluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCLinha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSalvar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jEdit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addGap(21, 21, 21))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jNome, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jrFeminino)
                    .addComponent(jrMasculino))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel8)
                            .addComponent(jCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jFone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jIdade, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel4)
                            .addComponent(jCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jRua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel14)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jExcluir)
                    .addComponent(jCLinha)
                    .addComponent(jSalvar)
                    .addComponent(jEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                .addGap(20, 20, 20))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jBairro, jCelular, jCep, jCidade, jCpf, jEmail, jEstado, jFone, jIdade, jNome, jNumero, jRua});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel2, jLabel3, jLabel5, jLabel6, jLabel9});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jCLinha, jEdit, jExcluir, jSalvar, jbCadastrar, jbLimpar, jbNovo});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jNomeActionPerformed

    public void ManipulaInterfaceDep() {
        switch (modoDep) {

            case "Novo":
                jbCadastrar.setEnabled(true);
                jbLimpar.setEnabled(true);
                jCLinha.setEnabled(false);
                jNome.setEnabled(true);
                jCpf.setEnabled(true);
                jFone.setEnabled(true);
                jIdade.setEnabled(true);
                jCidade.setEnabled(true);
                jCelular.setEnabled(true);
                jEmail.setEnabled(true);
                jCep.setEnabled(true);
                jEstado.setEnabled(true);
                jBairro.setEnabled(true);
                jNumero.setEnabled(true);
                jrMasculino.setEnabled(true);
                jrFeminino.setEnabled(true);
                jbNovo.setEnabled(false);
                jExcluir.setEnabled(false);
                jSalvar.setEnabled(false);
                jEdit.setEnabled(false);
                jRua.setEnabled(true);
                break;

            case "Editar":
                jbCadastrar.setEnabled(false);
                jbLimpar.setEnabled(true);
                jNome.setEnabled(true);
                jCpf.setEnabled(true);
                jFone.setEnabled(true);
                jIdade.setEnabled(true);
                jCidade.setEnabled(true);
                jCelular.setEnabled(true);
                jEmail.setEnabled(true);
                jCep.setEnabled(true);
                jEstado.setEnabled(true);
                jBairro.setEnabled(true);
                jNumero.setEnabled(true);
                jrMasculino.setEnabled(true);
                jrFeminino.setEnabled(true);
                jEdit.setEnabled(false);
                jbNovo.setEnabled(false);
                jCLinha.setEnabled(false);
                jExcluir.setEnabled(false);
                jSalvar.setEnabled(true);
                jRua.setEnabled(true);
                break;

            case "Excluir":
                jbNovo.setEnabled(true);
                jbCadastrar.setEnabled(false);
                jbLimpar.setEnabled(false);
                jCLinha.setEnabled(false);
                jNome.setEnabled(false);
                jCpf.setEnabled(false);
                jFone.setEnabled(false);
                jIdade.setEnabled(false);
                jCidade.setEnabled(false);
                jCelular.setEnabled(false);
                jEmail.setEnabled(false);
                jCep.setEnabled(false);
                jEstado.setEnabled(false);
                jBairro.setEnabled(false);
                jNumero.setEnabled(false);
                jrMasculino.setEnabled(false);
                jrFeminino.setEnabled(false);
                jExcluir.setEnabled(false);
                jSalvar.setEnabled(false);
                jEdit.setEnabled(false);
                jRua.setEnabled(false);
                break;

            case "Selecao":
                jbCadastrar.setEnabled(false);
                jbLimpar.setEnabled(false);
                jbNovo.setEnabled(true);
                jNome.setEnabled(false);
                jCpf.setEnabled(false);
                jFone.setEnabled(false);
                jIdade.setEnabled(false);
                jCidade.setEnabled(false);
                jCelular.setEnabled(false);
                jEmail.setEnabled(false);
                jCep.setEnabled(false);
                jEstado.setEnabled(false);
                jBairro.setEnabled(false);
                jNumero.setEnabled(false);
                jrMasculino.setEnabled(false);
                jrFeminino.setEnabled(false);
                jExcluir.setEnabled(true);
                jSalvar.setEnabled(false);
                jCLinha.setEnabled(true);
                jEdit.setEnabled(true);      
                jRua.setEnabled(false);
                break;
            default:
                JOptionPane.showMessageDialog(null, "Modo inválido");
        }
    }
    private void jbCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCadastrarActionPerformed

            LogicView();
            control.Valida.cpf();
        
        if (jNome.getText().isEmpty() || ("   .   .   -  ".equals(jCpf.getText()))) {
            JOptionPane.showMessageDialog(null, "Nome ou CPF não inserido.", "Não é possível cadastrar", JOptionPane.ERROR_MESSAGE);
        }else if(control.Valida.testa == false){
          
            modoDep = "Excluir";
            ManipulaInterfaceDep();

            ClienteDAO.insere(Cliente.v[0], Cliente.v[1], Cliente.v[2], Cliente.v[3], Cliente.v[4], Cliente.v[5], Cliente.v[6], Cliente.v[7], Cliente.v[8], Cliente.v[9], Cliente.v[10], Cliente.v[11], Cliente.v[12]);
            LoadTable();
            limpar();   
        }
        control.Valida.testa = false;
    }//GEN-LAST:event_jbCadastrarActionPerformed

    
    public void LogicView(){
            Cliente.v[0] = jNome.getText();
            Cliente.v[1] = jCpf.getText();
            Cliente.v[2] = jFone.getText();
            Cliente.v[3] = jIdade.getText();
            Cliente.v[4] = jCidade.getText();
            
            if (jrMasculino.isSelected()) {
                Cliente.v[5] = "Masculino";
                jrMasculino.setSelected(true);
                        
            } else if (jrFeminino.isSelected()) {
                Cliente.v[5] = "Feminino";
                jrFeminino.setSelected(true);
                
            } else {
                Cliente.v[5] = "NÃO INFORMADO";
            }
            
            Cliente.v[6] = jCelular.getText();
            Cliente.v[7] = jEmail.getText();
            Cliente.v[8] = jCep.getText();
            Cliente.v[9] = jEstado.getText();
            Cliente.v[10] = jBairro.getText();
            Cliente.v[11] = jNumero.getText();
            Cliente.v[12] = jRua.getText();
    }
    
    private void jIdadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jIdadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jIdadeActionPerformed

    private void jCidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCidadeActionPerformed

    private void jbLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLimparActionPerformed
        limpar();
    }//GEN-LAST:event_jbLimparActionPerformed

    private void jCpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCpfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCpfActionPerformed

    private void jFoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFoneActionPerformed

    private void jCelularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCelularActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCelularActionPerformed

    private void jCepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCepActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCepActionPerformed

    private void jNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNumeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jNumeroActionPerformed

    private void jbNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNovoActionPerformed
        modoDep = "Novo";
        ManipulaInterfaceDep();
        limpar();
    }//GEN-LAST:event_jbNovoActionPerformed

    private void jSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSalvarActionPerformed
            LogicView();
            salvar();
         ClienteDAO.atualiza(Cliente.v[0],Cliente.v[1], Cliente.v[2], Cliente.v[3], Cliente.v[4], Cliente.v[5], Cliente.v[6], Cliente.v[7], Cliente.v[8], Cliente.v[9], Cliente.v[10], Cliente.v[11], Cliente.v[12]);
    }//GEN-LAST:event_jSalvarActionPerformed
    
    public void salvar(){
         
        if(BackGround != Color.ORANGE){
            jTabela.setSelectionBackground(BackGround);
        }else{
            BackGround = jTabela.getSelectionBackground();
        }
        
        if (jNome.getText().isEmpty() || ("   .   .   -  ".equals(jCpf.getText()))) {
            JOptionPane.showMessageDialog(null, "Nome ou CPF não inserido.", "Não é possível cadastrar", JOptionPane.ERROR_MESSAGE);
        } else{
            
            index = jTabela.getSelectedRow(); 
            
            LogicView();
            ClienteWrite.salvar();
            
            modoDep = "Excluir";
            ManipulaInterfaceDep();
            limpar();
        }
    }
    
    private void jTabelaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabelaMouseClicked
           eventTable();          
    }//GEN-LAST:event_jTabelaMouseClicked

    private void jExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jExcluirActionPerformed
        jEdit.setEnabled(false);
        jExcluir.setEnabled(false);
        jCLinha.setEnabled(false);
        
        Modelo.limpar();

        limpar();
        ClienteDAO.cleartable();
    }//GEN-LAST:event_jExcluirActionPerformed

    private void jCLinhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCLinhaActionPerformed
        jExcluir.setEnabled(false);
        jCLinha.setEnabled(false);
        jEdit.setEnabled(false);
        index = jTabela.getSelectedRow();
        ClienteDAO.clearRow();
        Modelo.remove(index);
        ClienteWrite.cadastros.remove(index);
        limpar();
    }//GEN-LAST:event_jCLinhaActionPerformed
    public void limpar() {
        jNome.setText("");
        jCpf.setText("");
        jFone.setText("");
        jIdade.setText("");
        jCidade.setText("");
        jCelular.setText("");
        jEmail.setText("");
        jCep.setText("");
        jEstado.setText("");
        jBairro.setText("");
        jNumero.setText("");
        jRua.setText("");
    }
    private void jEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEditActionPerformed
        if(BackGround == Color.ORANGE){
            jTabela.setSelectionBackground(BackGround);
        }else if(BackGround == Color.CYAN){
            BackGround = jTabela.getSelectionBackground();
        }
        modoDep = "Editar";
        ManipulaInterfaceDep();
        jTabela.setSelectionBackground(Color.ORANGE);
    }//GEN-LAST:event_jEditActionPerformed

    private void jTabelaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTabelaKeyPressed

    }//GEN-LAST:event_jTabelaKeyPressed

    private void jTabelaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTabelaKeyReleased
        eventTable();
    }//GEN-LAST:event_jTabelaKeyReleased

    private void jTabelaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabelaMouseReleased
        eventTable();
    }//GEN-LAST:event_jTabelaMouseReleased
    
    public void eventTable(){
        
        if(BackGround != Color.ORANGE && BackGround != Color.CYAN){
            jTabela.setSelectionBackground(BackGround);
        }else{
            BackGround = jTabela.getSelectionBackground();
        } 
        
            int aux = jTabela.getSelectedRow();
            if (aux >= 0 && aux < Modelo.getRowCount()) {
                
                Cliente D = Modelo.getFuncionario(aux);

                jNome.setText(D.nome);
                jCpf.setText(D.cpf);
                jFone.setText(D.fone);
                jIdade.setText(D.idade);
                jCidade.setText(D.cidade);
                jCelular.setText(D.fonec);
                jEmail.setText(D.email);
                jCep.setText(D.cep);
                jEstado.setText(D.estado);
                jBairro.setText(D.bairro);
                jNumero.setText(D.numero);
                jRua.setText(D.rua);
                
                    if ("Masculino".equals(D.sexo)) {
                        jrMasculino.setSelected(true);
                    } else if ("Feminino".equals(D.sexo)) {
                        jrFeminino.setSelected(true);
                    }
                
                modoDep = "Selecao";
                ManipulaInterfaceDep();
            }

    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClienteView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClienteView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClienteView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClienteView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClienteView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup grupo_sexo;
    private javax.swing.JTextField jBairro;
    private javax.swing.JButton jCLinha;
    private javax.swing.JFormattedTextField jCelular;
    private javax.swing.JFormattedTextField jCep;
    private javax.swing.JTextField jCidade;
    private javax.swing.JFormattedTextField jCpf;
    private javax.swing.JButton jEdit;
    private javax.swing.JTextField jEmail;
    private javax.swing.JTextField jEstado;
    private javax.swing.JButton jExcluir;
    private javax.swing.JFormattedTextField jFone;
    private javax.swing.JTextField jIdade;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jNome;
    private javax.swing.JTextField jNumero;
    private javax.swing.JTextField jRua;
    private javax.swing.JButton jSalvar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTabela;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jbCadastrar;
    private javax.swing.JButton jbLimpar;
    private javax.swing.JButton jbNovo;
    private javax.swing.JRadioButton jrFeminino;
    private javax.swing.JRadioButton jrMasculino;
    // End of variables declaration//GEN-END:variables
}
