/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import control.Funcionario;
import model.FuncionarioWrite;
import dao.FuncionarioDAO;
import java.awt.Color;
import java.sql.Connection;
import javax.swing.JOptionPane;
import tablemodel.FuncionarioTM;

/**
 *
 * @author otavio
 */
public class FuncionarioView extends javax.swing.JFrame {

                //Gerador chama a class tabela e dá um nome
                public static FuncionarioTM Modelo;
            //..........................................
                
                public static int index;
                
            //Chama a class FuncionarioWrite e dá um nome
                FuncionarioWrite Logica;
            //........................................
                Connection con;
    
        public void LoadTable(){
        //Modelo recebe a criação de tabelas
            Modelo = new FuncionarioTM(FuncionarioDAO.funcionario());
        //..................................
        
        //Seta o conteúdo de modelo na tabela local
            jTabela.setModel(Modelo);
        //.........................................
        
        //Define as larguras de cada posição
        jTabela.getColumnModel().getColumn(0).setPreferredWidth(140);
        jTabela.getColumnModel().getColumn(1).setPreferredWidth(120);
        jTabela.getColumnModel().getColumn(2).setPreferredWidth(120);
        jTabela.getColumnModel().getColumn(3).setPreferredWidth(50);
        jTabela.getColumnModel().getColumn(4).setPreferredWidth(130);
        jTabela.getColumnModel().getColumn(5).setPreferredWidth(100);
        jTabela.getColumnModel().getColumn(6).setPreferredWidth(130);
        jTabela.getColumnModel().getColumn(7).setPreferredWidth(170);
        jTabela.getColumnModel().getColumn(8).setPreferredWidth(100);
        jTabela.getColumnModel().getColumn(9).setPreferredWidth(100);
        jTabela.getColumnModel().getColumn(10).setPreferredWidth(100);
        jTabela.getColumnModel().getColumn(11).setPreferredWidth(50);
        jTabela.getColumnModel().getColumn(12).setPreferredWidth(100);
        //..................................
    }            
    
    public FuncionarioView() {
        initComponents();
        
        LoadTable();
        
        setLocationRelativeTo(null);
        
        //Modo "Excluir" desativa a maioria dos botões
            modoDep = "Excluir";
        //..........................................
        
        //Chama a função do modoDep
            ManipulaInterfaceDep();
        //.........................     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jbNovo = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jSalvar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jExcluir = new javax.swing.JButton();
        jrMasculino = new javax.swing.JRadioButton();
        jCLinha = new javax.swing.JButton();
        jrFeminino = new javax.swing.JRadioButton();
        jbLimpar = new javax.swing.JButton();
        jEdit = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jCpf = new javax.swing.JFormattedTextField();
        jObservacao = new javax.swing.JTextField();
        jFone = new javax.swing.JFormattedTextField();
        jCelular = new javax.swing.JFormattedTextField();
        jLabel7 = new javax.swing.JLabel();
        jEmail = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jNome = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jBcadastrar = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jIdade = new javax.swing.JTextField();
        jNumero = new javax.swing.JTextField();
        jFuncao = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jDepartamento = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jSalario = new javax.swing.JTextField();
        jcData = new javax.swing.JFormattedTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTabela = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel4.setText("FUNÇÃO");

        jbNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/document-add.png"))); // NOI18N
        jbNovo.setText("Novo");
        jbNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNovoActionPerformed(evt);
            }
        });

        jLabel5.setText("FIXO");

        jSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/input-checked-outline.png"))); // NOI18N
        jSalvar.setText("Salvar alterações");
        jSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSalvarActionPerformed(evt);
            }
        });

        jLabel6.setText("IDADE");

        jExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/th-list-outline.png"))); // NOI18N
        jExcluir.setText("Limpar tabela");
        jExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jExcluirActionPerformed(evt);
            }
        });

        buttonGroup1.add(jrMasculino);
        jrMasculino.setText("Masculino");

        jCLinha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/user-delete-outline.png"))); // NOI18N
        jCLinha.setText("Limpar linha");
        jCLinha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCLinhaActionPerformed(evt);
            }
        });

        buttonGroup1.add(jrFeminino);
        jrFeminino.setText("Feminino");

        jbLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/trash.png"))); // NOI18N
        jbLimpar.setText("Limpar campos");
        jbLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLimparActionPerformed(evt);
            }
        });

        jEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/business-card.png"))); // NOI18N
        jEdit.setText("Editar");
        jEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEditActionPerformed(evt);
            }
        });

        jLabel13.setText("OBSERVAÇÃO");

        try {
            jCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jCpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCpfActionPerformed(evt);
            }
        });

        try {
            jFone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFoneActionPerformed(evt);
            }
        });

        try {
            jCelular.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) 9####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jCelular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCelularActionPerformed(evt);
            }
        });

        jLabel7.setText("CELULAR");

        jLabel8.setText("SALÁRIO");

        jLabel9.setText("E-MAIL");

        jNome.setToolTipText("");
        jNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNomeActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(0, 204, 255));
        jLabel1.setFont(new java.awt.Font("Quartz", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(73, 188, 227));
        jLabel1.setText("Cadastro de funcionário");

        jBcadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/group.png"))); // NOI18N
        jBcadastrar.setText("Cadastrar");
        jBcadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBcadastrarActionPerformed(evt);
            }
        });

        jLabel10.setText("DATA DE ENTRADA");
        jLabel10.setToolTipText("");

        jIdade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jIdadeActionPerformed(evt);
            }
        });

        jNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNumeroActionPerformed(evt);
            }
        });

        jFuncao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFuncaoActionPerformed(evt);
            }
        });

        jLabel11.setText("NÚMERO");

        jLabel2.setText("NOME");
        jLabel2.setToolTipText("");

        jLabel12.setText("DEPARTAMENTO");

        jLabel3.setText("CPF");

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/funcionario.png"))); // NOI18N

        jcData.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));
        jcData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcDataActionPerformed(evt);
            }
        });

        jTabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTabela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabelaMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jTabelaMouseReleased(evt);
            }
        });
        jTabela.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTabelaKeyReleased(evt);
            }
        });
        jScrollPane3.setViewportView(jTabela);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jIdade)
                                    .addComponent(jFone)
                                    .addComponent(jEmail)
                                    .addComponent(jCpf)
                                    .addComponent(jNome)
                                    .addComponent(jSalario))
                                .addGap(45, 45, 45)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jNumero, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jCelular, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jcData, javax.swing.GroupLayout.Alignment.TRAILING)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                                            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jDepartamento, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jFuncao, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jObservacao, javax.swing.GroupLayout.Alignment.TRAILING))))
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addComponent(jrMasculino, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(61, 61, 61)
                                        .addComponent(jrFeminino, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(64, 64, 64)
                                        .addComponent(jLabel14)))
                                .addGap(9, 9, 9)))
                        .addGap(27, 27, 27))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jbNovo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBcadastrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbLimpar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jExcluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCLinha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSalvar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jEdit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(35, 35, 35))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jNome, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jrFeminino)
                    .addComponent(jrMasculino))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jcData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jFone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jIdade, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jSalario)
                                    .addComponent(jLabel8)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel12))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jFuncao, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jObservacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel13))))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jBcadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jExcluir)
                            .addComponent(jCLinha)
                            .addComponent(jSalvar)
                            .addComponent(jEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel14))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                .addGap(20, 20, 20))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jCelular, jCpf, jDepartamento, jEmail, jFone, jFuncao, jIdade, jNome, jNumero, jObservacao, jSalario, jcData});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jBcadastrar, jCLinha, jEdit, jExcluir, jSalvar, jbLimpar, jbNovo});

        pack();
    }// </editor-fold>//GEN-END:initComponents
        public String modoDep;
        public void ManipulaInterfaceDep() {
        switch (modoDep) {

            case "Novo":
                jBcadastrar.setEnabled(true);
                jbLimpar.setEnabled(true);
                jCLinha.setEnabled(false);
                jNome.setEnabled(true);
                jCpf.setEnabled(true);
                jFone.setEnabled(true);
                jIdade.setEnabled(true);
                jFuncao.setEnabled(true);
                jCelular.setEnabled(true);
                jEmail.setEnabled(true);
                jDepartamento.setEnabled(true);
                jcData.setEnabled(true);
                jSalario.setEnabled(true);
                jNumero.setEnabled(true);
                jrMasculino.setEnabled(true);
                jrFeminino.setEnabled(true);
                jbNovo.setEnabled(false);
                jExcluir.setEnabled(false);
                jSalvar.setEnabled(false);
                jEdit.setEnabled(false);
                jObservacao.setEnabled(true);
                break;

            case "Editar":
                jBcadastrar.setEnabled(false);
                jbLimpar.setEnabled(true);
                jNome.setEnabled(true);
                jCpf.setEnabled(true);
                jFone.setEnabled(true);
                jIdade.setEnabled(true);
                jFuncao.setEnabled(true);
                jCelular.setEnabled(true);
                jEmail.setEnabled(true);
                jDepartamento.setEnabled(true);
                jcData.setEnabled(true);
                jSalario.setEnabled(true);
                jNumero.setEnabled(true);
                jrMasculino.setEnabled(true);
                jrFeminino.setEnabled(true);
                jEdit.setEnabled(false);
                jbNovo.setEnabled(false);
                jCLinha.setEnabled(false);
                jExcluir.setEnabled(false);
                jSalvar.setEnabled(true);
                jObservacao.setEnabled(true);
                break;

            case "Excluir":
                jbNovo.setEnabled(true);
                jBcadastrar.setEnabled(false);
                jbLimpar.setEnabled(false);
                jCLinha.setEnabled(false);
                jNome.setEnabled(false);
                jCpf.setEnabled(false);
                jFone.setEnabled(false);
                jIdade.setEnabled(false);
                jFuncao.setEnabled(false);
                jCelular.setEnabled(false);
                jEmail.setEnabled(false);
                jDepartamento.setEnabled(false);
                jSalario.setEnabled(false);
                jcData.setEnabled(false);
                jNumero.setEnabled(false);
                jrMasculino.setEnabled(false);
                jrFeminino.setEnabled(false);
                jExcluir.setEnabled(false);
                jSalvar.setEnabled(false);
                jEdit.setEnabled(false);
                jObservacao.setEnabled(false);
                break;

            case "Selecao":
                jBcadastrar.setEnabled(false);
                jbLimpar.setEnabled(false);
                jbNovo.setEnabled(true);
                jNome.setEnabled(false);
                jCpf.setEnabled(false);
                jFone.setEnabled(false);
                jIdade.setEnabled(false);
                jFuncao.setEnabled(false);
                jCelular.setEnabled(false);
                jEmail.setEnabled(false);
                jDepartamento.setEnabled(false);
                jcData.setEnabled(false);
                jSalario.setEnabled(false);
                jNumero.setEnabled(false);
                jrMasculino.setEnabled(false);
                jrFeminino.setEnabled(false);
                jExcluir.setEnabled(true);
                jSalvar.setEnabled(false);
                jCLinha.setEnabled(true);
                jEdit.setEnabled(true);      
                jObservacao.setEnabled(false);
                break;
            default:
                JOptionPane.showMessageDialog(null, "Modo inválido");
        }
    }
        
        
       public void limpar() {
        jNome.setText("");
        jCpf.setText("");
        jFone.setText("");
        jIdade.setText("");
        jFuncao.setText("");
        jCelular.setText("");
        jEmail.setText("");
        jcData.setText("");
        jDepartamento.setText("");
        jSalario.setText("");
        jNumero.setText("");
        jObservacao.setText("");
    }
    
    private void jbNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNovoActionPerformed
        limpar();
        modoDep = "Novo";
        ManipulaInterfaceDep();
    }//GEN-LAST:event_jbNovoActionPerformed

    private void jSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSalvarActionPerformed
        LogicView();
        salvar();
        FuncionarioDAO.atualiza(Funcionario.v[0], Funcionario.v[1], Funcionario.v[2], Funcionario.v[3], Funcionario.v[4], Funcionario.v[5], Funcionario.v[6], Funcionario.v[7], Funcionario.v[8], Funcionario.v[9], Funcionario.v[10], Funcionario.v[11], Funcionario.v[12]);
    }//GEN-LAST:event_jSalvarActionPerformed

    private void jExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jExcluirActionPerformed
        
        jEdit.setEnabled(false);
        jExcluir.setEnabled(false);
        jCLinha.setEnabled(false);
        
        Modelo.limpar();

        while (FuncionarioWrite.cadastros.size() > 0) {
            FuncionarioWrite.cadastros.clear();
        }
        limpar();
        
        FuncionarioDAO.cleartable();
    }//GEN-LAST:event_jExcluirActionPerformed

    private void jCLinhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCLinhaActionPerformed
        index = jTabela.getSelectedRow();
        FuncionarioDAO.clearRow();
        
        Modelo.remove(index);
        FuncionarioWrite.cadastros.remove(index);
        limpar();

        jExcluir.setEnabled(false);
        jCLinha.setEnabled(false);
        jEdit.setEnabled(false);
    }//GEN-LAST:event_jCLinhaActionPerformed

    private void jbLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLimparActionPerformed
        limpar();
    }//GEN-LAST:event_jbLimparActionPerformed

    private void jEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEditActionPerformed
        
        if(BackGround == Color.ORANGE){
            jTabela.setSelectionBackground(BackGround);
        }else if(BackGround == Color.CYAN){
            BackGround = jTabela.getSelectionBackground();
        }
        modoDep = "Editar";
        ManipulaInterfaceDep();
        jTabela.setSelectionBackground(Color.ORANGE);

        modoDep = "Editar";
        ManipulaInterfaceDep();
    }//GEN-LAST:event_jEditActionPerformed

    private void jCpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCpfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCpfActionPerformed

    private void jFoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFoneActionPerformed

    private void jCelularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCelularActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCelularActionPerformed

    private void jNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jNomeActionPerformed

    
    public void LogicView(){
            Funcionario.v[0] = jNome.getText();
            Funcionario.v[1] = jCpf.getText();
            Funcionario.v[2] = jEmail.getText();
            Funcionario.v[3] = jFone.getText();
            Funcionario.v[4] = jIdade.getText();         
            Funcionario.v[5] = jSalario.getText();
            Funcionario.v[6] = jCelular.getText();
            Funcionario.v[7] = jNumero.getText();
            Funcionario.v[8] = jcData.getText();
            Funcionario.v[9] = jDepartamento.getText();
            Funcionario.v[10] = jFuncao.getText();
            Funcionario.v[11] = jObservacao.getText();
            
            if (jrMasculino.isSelected()) {
                Funcionario.v[12] = "Masculino";
                jrMasculino.setSelected(true);
                        
            } else if (jrFeminino.isSelected()) {
                Funcionario.v[12] = "Feminino";
                jrFeminino.setSelected(true);
                
            } else {
                Funcionario.v[12] = "NÃO INFORMADO";
            }
    }
    
    private void jIdadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jIdadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jIdadeActionPerformed

    private void jNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNumeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jNumeroActionPerformed

    private void jFuncaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFuncaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFuncaoActionPerformed

    private void jcDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcDataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcDataActionPerformed

    private void jBcadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBcadastrarActionPerformed
        
        LogicView();
        control.Valida.cpff();
        
        if (jNome.getText().isEmpty() || ("   .   .   -  ".equals(jCpf.getText()))) {
            JOptionPane.showMessageDialog(null, "Nome ou CPF não inserido.", "Não é possível cadastrar", JOptionPane.ERROR_MESSAGE);
        } else if (control.Valida.testa == false) {
            
            modoDep = "Excluir";
            ManipulaInterfaceDep();
            
            FuncionarioDAO.insere(Funcionario.v[0], Funcionario.v[1], Funcionario.v[2], Funcionario.v[3], Funcionario.v[4], Funcionario.v[5], Funcionario.v[6], Funcionario.v[7], Funcionario.v[8], Funcionario.v[9], Funcionario.v[10], Funcionario.v[11], Funcionario.v[12]);
            LoadTable();
            limpar();
             
        }

        control.Valida.testa = false;
    }//GEN-LAST:event_jBcadastrarActionPerformed

    private void jTabelaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabelaMouseClicked
        eventTable();
    }//GEN-LAST:event_jTabelaMouseClicked

    private void jTabelaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTabelaKeyReleased
        eventTable();
    }//GEN-LAST:event_jTabelaKeyReleased

    private void jTabelaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabelaMouseReleased
       eventTable();
    }//GEN-LAST:event_jTabelaMouseReleased

        Color BackGround = Color.CYAN;
    
        public void salvar(){
         
        if(BackGround != Color.ORANGE){
            jTabela.setSelectionBackground(BackGround);
        }else{
            BackGround = jTabela.getSelectionBackground();
        }
        
        if (jNome.getText().isEmpty() || ("   .   .   -  ".equals(jCpf.getText()))) {
            JOptionPane.showMessageDialog(null, "Nome ou CPF não inserido.", "Não é possível cadastrar", JOptionPane.ERROR_MESSAGE);
        } else {
            
            index = jTabela.getSelectedRow(); 
            
            LogicView();
            FuncionarioWrite.salvar();
            
            modoDep = "Excluir";
            ManipulaInterfaceDep();
            limpar();
        }
    }
        
            public void eventTable(){
        
        if(BackGround != Color.ORANGE && BackGround != Color.CYAN){
            jTabela.setSelectionBackground(BackGround);
        }else{
            BackGround = jTabela.getSelectionBackground();
        } 
        
            int aux = jTabela.getSelectedRow();
            if (aux >= 0 && aux < Modelo.getRowCount()) {
                
                Funcionario D = Modelo.getFuncionario(aux);

                jNome.setText(D.nome);
                jCpf.setText(D.cpf);
                jEmail.setText(D.email);
                jFone.setText(D.fone);
                jIdade.setText(D.idade);
                jSalario.setText(D.salario);
                jCelular.setText(D.fonec);
                jNumero.setText(D.numero);
                jcData.setText(D.data);
                jDepartamento.setText(D.departamento);
                jFuncao.setText(D.funcao);
                jObservacao.setText(D.observacao);
                
                    if ("Masculino".equals(D.sexo)) {
                        jrMasculino.setSelected(true);
                    } else if ("Feminino".equals(D.sexo)) {
                        jrFeminino.setSelected(true);
                    }
                
                modoDep = "Selecao";
                ManipulaInterfaceDep();
            }

    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FuncionarioView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FuncionarioView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FuncionarioView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FuncionarioView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FuncionarioView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jBcadastrar;
    private javax.swing.JButton jCLinha;
    private javax.swing.JFormattedTextField jCelular;
    private javax.swing.JFormattedTextField jCpf;
    private javax.swing.JTextField jDepartamento;
    private javax.swing.JButton jEdit;
    private javax.swing.JTextField jEmail;
    private javax.swing.JButton jExcluir;
    private javax.swing.JFormattedTextField jFone;
    private javax.swing.JTextField jFuncao;
    private javax.swing.JTextField jIdade;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jNome;
    private javax.swing.JTextField jNumero;
    private javax.swing.JTextField jObservacao;
    private javax.swing.JTextField jSalario;
    private javax.swing.JButton jSalvar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTabela;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jbLimpar;
    private javax.swing.JButton jbNovo;
    private javax.swing.JFormattedTextField jcData;
    private javax.swing.JRadioButton jrFeminino;
    private javax.swing.JRadioButton jrMasculino;
    // End of variables declaration//GEN-END:variables
}
