/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Color;
import javax.swing.JOptionPane;
import control.Produto;
import tablemodel.ProdutoTM;
import model.ProdutoWrite;
import dao.ProdutoDAO;
/**
 *
 * @author aluno
 */
public class ProdutosView extends javax.swing.JFrame {
            //Gerador chama a class tabela e dá um nome
                public static ProdutoTM Modelo;
                public boolean aux = true;
                public static String escolha1 = "";
            //.........................................
                
    public ProdutosView() {
        initComponents();
        LoadTable();
        setLocationRelativeTo(null);
        
        //Modo "Excluir" desativa a maioria dos botões
            modoDep = "Excluir";
            ManipulaInterfaceDep();
            modoDep = "test";
            ManipulaInterfaceDep();
        //..........................................
    }
    public static int index;
    
        public void LoadTable(){
            if(aux == true){
        //Modelo recebe a criação de tabelas
                Modelo = new ProdutoTM(ProdutoDAO.produtos());
        //..................................
            }else{
                Modelo = new ProdutoTM(ProdutoDAO.pesquisa());
            }
        //Seta o conteúdo de modelo na tabela local
            jTabela.setModel(Modelo);
        //.........................................
            
        //Define as larguras de cada posição
        jTabela.getColumnModel().getColumn(0).setPreferredWidth(200);
        jTabela.getColumnModel().getColumn(1).setPreferredWidth(50);
        jTabela.getColumnModel().getColumn(2).setPreferredWidth(30);
        jTabela.getColumnModel().getColumn(3).setPreferredWidth(30);
        jTabela.getColumnModel().getColumn(4).setPreferredWidth(30);
        jTabela.getColumnModel().getColumn(5).setPreferredWidth(200);
        jTabela.getColumnModel().getColumn(6).setPreferredWidth(40);
        jTabela.getColumnModel().getColumn(7).setPreferredWidth(10);
        jTabela.getColumnModel().getColumn(8).setPreferredWidth(5);
        //..................................
    }
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTabela = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        menos = new javax.swing.JButton();
        mais = new javax.swing.JButton();
        jQuantidade = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jNome = new javax.swing.JTextField();
        jCodigoProduto = new javax.swing.JTextField();
        jValorCompra = new javax.swing.JTextField();
        jMarca = new javax.swing.JTextField();
        jDescricao = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jData = new javax.swing.JFormattedTextField();
        jcFornecedor = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jValorVenda = new javax.swing.JTextField();
        jCategoria = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPrateleira = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jEdit = new javax.swing.JButton();
        jbLimpar = new javax.swing.JButton();
        jbCadastrar = new javax.swing.JButton();
        jbNovo = new javax.swing.JButton();
        jSalvar = new javax.swing.JButton();
        jExcluir = new javax.swing.JButton();
        jCLinha = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        escolha = new javax.swing.JComboBox<>();
        jPesquisa = new javax.swing.JTextField();
        jPesquisar = new javax.swing.JButton();
        jLoad = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 204, 255));
        jLabel8.setText("Cadastro de produtos");

        jTabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Código do produto", "Valor da compra", "Data da compra", "Fornecedor", "Valor da venda", "Descrição", "Fornecedor", "Prateleira"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTabela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jTabelaMouseReleased(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabelaMouseClicked(evt);
            }
        });
        jTabela.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTabelaKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTabela);

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        menos.setText("-");
        menos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menosActionPerformed(evt);
            }
        });

        mais.setText("+");
        mais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maisActionPerformed(evt);
            }
        });

        jQuantidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jQuantidadeActionPerformed(evt);
            }
        });

        jLabel14.setText("Quantidade");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jQuantidade)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(menos, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(mais)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {mais, menos});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(menos)
                    .addComponent(mais))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {mais, menos});

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel6.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jCodigoProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCodigoProdutoActionPerformed(evt);
            }
        });

        jDescricao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDescricaoActionPerformed(evt);
            }
        });

        jLabel1.setText("NOME DO PRODUTO");

        jLabel2.setText("CÓDIGO DO PRODUTO");

        jLabel3.setText("VALOR DA COMPRA");

        jLabel9.setText("MARCA");

        jLabel6.setText("DESCRIÇÃO");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jMarca, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                    .addComponent(jDescricao)
                    .addComponent(jCodigoProduto, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jValorCompra, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jNome, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );

        jPanel6Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel1, jLabel2, jLabel3, jLabel6, jLabel9});

        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCodigoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jValorCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addContainerGap())
        );

        jPanel6Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel1, jLabel2, jLabel3, jLabel6, jLabel9});

        jPanel6Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jCodigoProduto, jDescricao, jMarca, jNome, jValorCompra});

        jPanel7.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jLabel7.setText("DATA DA COMPRA");

        try {
            jData.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDataActionPerformed(evt);
            }
        });

        jLabel5.setText("FORNECEDOR");

        jLabel4.setText("VALOR DA VENDA");

        jValorVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jValorVendaActionPerformed(evt);
            }
        });

        jLabel10.setText("CATEGORIA");

        jLabel13.setText("PRATELEIRA");

        jPrateleira.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPrateleiraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jcFornecedor)
                            .addComponent(jValorVenda)
                            .addComponent(jData, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                            .addComponent(jCategoria)))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPrateleira)))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGap(0, 15, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jcFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jValorVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPrateleira, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel7Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel10, jLabel13, jLabel4, jLabel5, jLabel7});

        jPanel7Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jCategoria, jData, jPrateleira, jValorVenda, jcFornecedor});

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jPanel6, jPanel7});

        jPanel5.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jPanel4.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/business-card.png"))); // NOI18N
        jEdit.setText("Editar");
        jEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEditActionPerformed(evt);
            }
        });

        jbLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/trash.png"))); // NOI18N
        jbLimpar.setText("Limpar campos");
        jbLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLimparActionPerformed(evt);
            }
        });

        jbCadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pen.png"))); // NOI18N
        jbCadastrar.setText("Cadastrar");
        jbCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCadastrarActionPerformed(evt);
            }
        });

        jbNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/document-add.png"))); // NOI18N
        jbNovo.setText("Novo");
        jbNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNovoActionPerformed(evt);
            }
        });

        jSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/input-checked-outline.png"))); // NOI18N
        jSalvar.setText("Salvar alterações");
        jSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSalvarActionPerformed(evt);
            }
        });

        jExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/th-list-outline.png"))); // NOI18N
        jExcluir.setText("Limpar tabela");
        jExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jExcluirActionPerformed(evt);
            }
        });

        jCLinha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/minus-outline.png"))); // NOI18N
        jCLinha.setText("Limpar linha");
        jCLinha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCLinhaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addComponent(jbNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbCadastrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbLimpar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jExcluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCLinha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSalvar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbCadastrar)
                    .addComponent(jbLimpar)
                    .addComponent(jbNovo)
                    .addComponent(jExcluir)
                    .addComponent(jCLinha)
                    .addComponent(jSalvar)
                    .addComponent(jEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel4Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jCLinha, jEdit, jExcluir, jSalvar, jbCadastrar, jbLimpar, jbNovo});

        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        escolha.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nome", "Marca", "Categoria", "Fornecedor", "Prateleira", "Descricao" }));
        escolha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                escolhaActionPerformed(evt);
            }
        });

        jPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/zoom.png"))); // NOI18N
        jPesquisar.setText("Pesquisar");
        jPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPesquisarActionPerformed(evt);
            }
        });

        jLoad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/document-text.png"))); // NOI18N
        jLoad.setText("Recarregar tabela");
        jLoad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLoadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(escolha, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPesquisa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLoad)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(escolha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLoad)
                .addComponent(jPesquisar))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {escolha, jLoad, jPesquisa, jPesquisar});

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel8.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 198, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCLinhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCLinhaActionPerformed
        int sen = JOptionPane.showConfirmDialog(null, "Deseja apagar essa linha?");
        
        if(0==sen){
        jExcluir.setEnabled(false);
        jCLinha.setEnabled(false);
        jEdit.setEnabled(false);
        index = jTabela.getSelectedRow();
        ProdutoDAO.clearRow();
        Modelo.remove(index);
        ProdutoWrite.produtos.remove(index);
        limpar();
        }
        
    modoDep = "test";
    ManipulaInterfaceDep();
        
    }//GEN-LAST:event_jCLinhaActionPerformed

    private void jEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEditActionPerformed
        int aux = jTabela.getSelectedRow();
        jValorCompra.setText(Modelo.getFuncionario(aux).valor_da_compra);
        if(BackGround == Color.ORANGE){
            jTabela.setSelectionBackground(BackGround);
        }else if(BackGround == Color.CYAN){
            BackGround = jTabela.getSelectionBackground();
        }
        modoDep = "Editar";
        ManipulaInterfaceDep();
        jTabela.setSelectionBackground(Color.ORANGE);
    }//GEN-LAST:event_jEditActionPerformed

    private void jbLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLimparActionPerformed
            limpar();
    }//GEN-LAST:event_jbLimparActionPerformed

    private void jbCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCadastrarActionPerformed
        
        jCodigoProduto.setText("");
        LoadTable();
        
        LogicView();
        control.Valida.produto();
        
        if (jNome.getText().isEmpty() || "  /  /    ".equals(jData.getText())) {
            JOptionPane.showMessageDialog(null, "Nome ou Data da compra não inserido.", "Não é possível cadastrar", JOptionPane.ERROR_MESSAGE);
        } else if(control.Valida.testa == false) {

        modoDep = "Excluir";
        ManipulaInterfaceDep();            
            
        ProdutoDAO.insere(Produto.v[0], Produto.v[2], Produto.v[3], Produto.v[4], Produto.v[5], Produto.v[6], Produto.v[7], Produto.v[8], Produto.v[9], Produto.v[10]);
        aux = true;
        LoadTable();
        
                jLoad.setEnabled(true);
                jPesquisar.setEnabled(true);
                jPesquisa.setEnabled(true);
                escolha.setEnabled(true);
        }
        
        control.Valida.testa = false;
    }//GEN-LAST:event_jbCadastrarActionPerformed

    private void jbNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNovoActionPerformed
        limpar();
        modoDep = "Novo";
        ManipulaInterfaceDep();
    }//GEN-LAST:event_jbNovoActionPerformed

    private void jExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jExcluirActionPerformed
        
        String sen = JOptionPane.showInputDialog(null, "Digite a senha:");
        
        if("ooo".equals(sen)){

                Modelo.limpar();
            while (ProdutoWrite.produtos.size() > 0) {
                ProdutoWrite.produtos.clear();
            }
            limpar();
            jEdit.setEnabled(false);
            jExcluir.setEnabled(false);
            jCLinha.setEnabled(false);

            ProdutoDAO.cleartable();
        
        }else{JOptionPane.showMessageDialog(null, "Senha inválida");}
        
        modoDep = "test";
        ManipulaInterfaceDep();
    }//GEN-LAST:event_jExcluirActionPerformed

    private void jSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSalvarActionPerformed
        LogicView();
        salvar(); 
        ProdutoDAO.atualiza(Produto.v[0], Produto.v[1], Produto.v[2], Produto.v[3], Produto.v[4], Produto.v[5], Produto.v[6], Produto.v[7], Produto.v[8], Produto.v[9], Produto.v[10]);
    }//GEN-LAST:event_jSalvarActionPerformed

    private void jTabelaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabelaMouseClicked
       eventTable();
    }//GEN-LAST:event_jTabelaMouseClicked

    private void jPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPesquisarActionPerformed
        jEdit.setEnabled(false);
        jCLinha.setEnabled(false);
        limpar();
        
        escolha1 = escolha.getSelectedItem().toString();
        Produto.pesquisa = jPesquisa.getText().toUpperCase().trim().replace('Ç','C');
        aux = false;
        LoadTable();
    }//GEN-LAST:event_jPesquisarActionPerformed

    private void jLoadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLoadActionPerformed
        jEdit.setEnabled(false);
        jCLinha.setEnabled(false);
        jPesquisa.setText("");
        limpar();
        aux = true;
        LoadTable();
    }//GEN-LAST:event_jLoadActionPerformed

    private void jQuantidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jQuantidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jQuantidadeActionPerformed

    private void jTabelaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTabelaKeyReleased
        eventTable();
    }//GEN-LAST:event_jTabelaKeyReleased

    private void jTabelaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabelaMouseReleased
        eventTable();
    }//GEN-LAST:event_jTabelaMouseReleased

    private void escolhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_escolhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_escolhaActionPerformed

    private void menosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menosActionPerformed
        int quant = Integer.parseInt(jQuantidade.getText());
        quant--;
        jQuantidade.setText(quant+"");
    }//GEN-LAST:event_menosActionPerformed

    private void maisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maisActionPerformed
        int quant = Integer.parseInt(jQuantidade.getText());
        quant++;
        jQuantidade.setText(quant+"");
    }//GEN-LAST:event_maisActionPerformed

    private void jPrateleiraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPrateleiraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPrateleiraActionPerformed

    private void jValorVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jValorVendaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jValorVendaActionPerformed

    private void jDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jDataActionPerformed

    private void jDescricaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDescricaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jDescricaoActionPerformed

    private void jCodigoProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCodigoProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCodigoProdutoActionPerformed

    public void LogicView(){
            Produto.v[0] = jNome.getText().toUpperCase().trim().replace('Ç','C');
            Produto.v[1] = jCodigoProduto.getText();
            Produto.v[2] = jValorCompra.getText().toUpperCase().trim().replace('Ç','C');
            Produto.v[3] = jMarca.getText().toUpperCase().trim().replace('Ç','C');
            Produto.v[4] = jData.getText();
            Produto.v[5] = jValorVenda.getText().toUpperCase().trim().replace('Ç','C');
            Produto.v[6] = jCategoria.getText().toUpperCase().trim().replace('Ç','C');
            Produto.v[7] = jDescricao.getText().toUpperCase().trim().replace('Ç','C');
            Produto.v[8] = jcFornecedor.getText().toUpperCase().trim().replace('Ç','C');
            Produto.v[9] = jPrateleira.getText().toUpperCase().trim().replace('Ç','C');
            Produto.v[10]= jQuantidade.getText().toUpperCase().trim().replace('Ç','C');
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProdutosView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProdutosView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProdutosView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProdutosView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProdutosView().setVisible(true);
            }
        });
    }
    
     public void limpar() {
                jNome.setText("");
                jQuantidade.setText("");
                jValorCompra.setText("");
                jMarca.setText("");
                jData.setText("");
                jValorVenda.setText("");
                jCategoria.setText("");
                jDescricao.setText("");
                jcFornecedor.setText("");
                jPrateleira.setText("");
    }

        public String modoDep;
    
        public void ManipulaInterfaceDep() {
            
            int aux = jTabela.getRowCount();
            
            
        switch (modoDep) {
            
            case "Novo":
                jbCadastrar.setEnabled(true);
                jbLimpar.setEnabled(true);
                jCLinha.setEnabled(false);
                
                jLoad.setEnabled(false);
                jPesquisar.setEnabled(false);
                jPesquisa.setEnabled(false);
                escolha.setEnabled(false);
                
                jNome.setEnabled(true);
                jQuantidade.setEnabled(true);
                menos.setEnabled(true);
                mais.setEnabled(true);
                jCodigoProduto.setEnabled(false);
                jValorCompra.setEnabled(true);
                jMarca.setEnabled(true);
                jData.setEnabled(true);
                jValorVenda.setEnabled(true);
                jCategoria.setEnabled(true);
                jDescricao.setEnabled(true);
                jcFornecedor.setEnabled(true);
                jPrateleira.setEnabled(true);
                
                jbNovo.setEnabled(false);
                jExcluir.setEnabled(false);
                jSalvar.setEnabled(false);
                jEdit.setEnabled(false);

                break;

            case "Editar":
                jbCadastrar.setEnabled(false);
                jbLimpar.setEnabled(true);
                
                jLoad.setEnabled(false);
                jPesquisar.setEnabled(false);
                jPesquisa.setEnabled(false);
                escolha.setEnabled(false);
                
                jNome.setEnabled(true);
                jQuantidade.setEnabled(true);
                menos.setEnabled(true);
                mais.setEnabled(true);
                jCodigoProduto.setEnabled(false);
                jValorCompra.setEnabled(true);
                jMarca.setEnabled(true);
                jData.setEnabled(true);
                jValorVenda.setEnabled(true);
                jCategoria.setEnabled(true);
                jDescricao.setEnabled(true);
                jcFornecedor.setEnabled(true);
                jPrateleira.setEnabled(true);
                
                jEdit.setEnabled(false);
                jbNovo.setEnabled(false);
                jCLinha.setEnabled(false);
                jExcluir.setEnabled(false);
                jSalvar.setEnabled(true);

                break;

            case "Excluir":
                jbNovo.setEnabled(true);
                jbCadastrar.setEnabled(false);
                jbLimpar.setEnabled(false);
                jCLinha.setEnabled(false);
                
                jNome.setEnabled(false);
                jQuantidade.setEnabled(false);
                menos.setEnabled(false);
                mais.setEnabled(false);
                jCodigoProduto.setEnabled(false);
                jValorCompra.setEnabled(false);
                jMarca.setEnabled(false);
                jData.setEnabled(false);
                jValorVenda.setEnabled(false);
                jCategoria.setEnabled(false);
                jDescricao.setEnabled(false);
                jcFornecedor.setEnabled(false);
                jPrateleira.setEnabled(false);
                
                jExcluir.setEnabled(false);
                jSalvar.setEnabled(false);
                jEdit.setEnabled(false);

                break;

            case "Selecao":
                jbCadastrar.setEnabled(false);
                jbLimpar.setEnabled(false);
                jbNovo.setEnabled(true);
                
                jNome.setEnabled(false);
                jQuantidade.setEnabled(false);
                menos.setEnabled(false);
                mais.setEnabled(false);
                jCodigoProduto.setEnabled(false);
                jValorCompra.setEnabled(false);
                jMarca.setEnabled(false);
                jData.setEnabled(false);
                jValorVenda.setEnabled(false);
                jCategoria.setEnabled(false);
                jDescricao.setEnabled(false);
                jcFornecedor.setEnabled(false);
                jPrateleira.setEnabled(false);
                
                jExcluir.setEnabled(true);
                jSalvar.setEnabled(false);
                jCLinha.setEnabled(true);
                jEdit.setEnabled(true);      

                jLoad.setEnabled(true);
                jPesquisar.setEnabled(true);
                jPesquisa.setEnabled(true);
                escolha.setEnabled(true);
                break;
                
            case "test":
                if(aux == 0){
                jLoad.setEnabled(false);
                jPesquisar.setEnabled(false);
                jPesquisa.setEnabled(false);
                escolha.setEnabled(false);
            }else{
                jLoad.setEnabled(true);
                jPesquisar.setEnabled(true);
                jPesquisa.setEnabled(true);
                escolha.setEnabled(true);
            }
                break;
            default:
                JOptionPane.showMessageDialog(null, "Modo inválido");
        }
    }
        public Color BackGround = Color.CYAN;
        
            public void salvar(){
         
        if(BackGround != Color.ORANGE){
            jTabela.setSelectionBackground(BackGround);
        }else{
            BackGround = jTabela.getSelectionBackground();
        }
        
        if (jNome.getText().isEmpty() || jCodigoProduto.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Nome não inserido.", "Não é possível cadastrar", JOptionPane.ERROR_MESSAGE);
        } else {
            
            index = jTabela.getSelectedRow(); 
            
            LogicView();
            ProdutoWrite.salvar();
            
            modoDep = "Excluir";
            ManipulaInterfaceDep();
            limpar();
        }
        control.Valida.testa = false;
    }
        
        public void eventTable(){
        
        if(BackGround != Color.ORANGE && BackGround != Color.CYAN){
            jTabela.setSelectionBackground(BackGround);
        }else{
            BackGround = jTabela.getSelectionBackground();
        } 
        
            int aux = jTabela.getSelectedRow();
            if (aux >= 0 && aux < Modelo.getRowCount()) {
                
                Produto D = Modelo.getFuncionario(aux);

                jNome.setText(D.nome);
                jCodigoProduto.setText(D.codigo_produto);
                jValorCompra.setText(D.valor_da_compra);
                jMarca.setText(D.marca);
                jData.setText(D.data_da_compra);
                jValorVenda.setText(D.valor_da_venda);
                jCategoria.setText(D.categoria);
                jDescricao.setText(D.descricao);
                jcFornecedor.setText(D.fornecedor);
                jPrateleira.setText(D.prateleira);
                jQuantidade.setText(D.quant);
                
                modoDep = "Selecao";
                ManipulaInterfaceDep();
            }

    }        
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> escolha;
    private javax.swing.JButton jCLinha;
    private javax.swing.JTextField jCategoria;
    private javax.swing.JTextField jCodigoProduto;
    private javax.swing.JFormattedTextField jData;
    private javax.swing.JTextField jDescricao;
    private javax.swing.JButton jEdit;
    private javax.swing.JButton jExcluir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton jLoad;
    private javax.swing.JTextField jMarca;
    private javax.swing.JTextField jNome;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JTextField jPesquisa;
    private javax.swing.JButton jPesquisar;
    private javax.swing.JTextField jPrateleira;
    private javax.swing.JTextField jQuantidade;
    private javax.swing.JButton jSalvar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTabela;
    private javax.swing.JTextField jValorCompra;
    private javax.swing.JTextField jValorVenda;
    private javax.swing.JButton jbCadastrar;
    private javax.swing.JButton jbLimpar;
    private javax.swing.JButton jbNovo;
    private javax.swing.JTextField jcFornecedor;
    private javax.swing.JButton mais;
    private javax.swing.JButton menos;
    // End of variables declaration//GEN-END:variables
}
